---
repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.48.0
    hooks:
      - id: eslint
        additional_dependencies:
          - eslint@8.3.0
          - eslint-config-next@12.0.0
          - eslint-config-prettier@8.3.0
          - eslint-plugin-jest-dom@4.0.0
          - eslint-plugin-prettier@3.0.0
          - eslint-plugin-storybook@0.5.6
          - eslint-plugin-tailwindcss@3.5.0
          - eslint-plugin-testing-library@5.0.6
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
        files: \.([jt]sx?|yaml|yml|md)$  # *.js, *.jsx, *.ts, *.tsx, *.yaml, *.yml and *.md
        types: [file]
      - id: end-of-file-fixer
        files: \.([jt]sx?|yaml|yml|md)$  # *.js, *.jsx, *.ts, *.tsx, *.yaml, *.yml and *.md
        types: [file]
      - id: mixed-line-ending
        files: \.([jt]sx?|yaml|yml|md)$  # *.js, *.jsx, *.ts, *.tsx, *.yaml, *.yml and *.md
        types: [file]
      - id: fix-byte-order-marker
        files: \.([jt]sx?|yaml|yml|md)$  # *.js, *.jsx, *.ts, *.tsx, *.yaml, *.yml and *.md
        types: [file]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.36.0
    hooks:
      - id: markdownlint
        files: \.md$
        types: [file]
        args:
          - --config
          - ./markdownlint.yaml
  - repo: https://github.com/sirosen/texthooks
    rev: 0.4.0
    hooks:
      - id: fix-smartquotes
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [file]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        files: \.(yaml|yml)$
        types: [file]
