---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: &app zigbee2mqtt-basement
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: false
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    global:
      nameOverride: *app
    image:
      repository: ghcr.io/koenkk/zigbee2mqtt
      tag: 1.35.3
    env:
      ZIGBEE2MQTT_DATA: /config
      TZ: ${SETTING_TZ}
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        existingClaim: zigbee2mqtt-basement-data
        mountPath: /config
    resources:
      requests:
        cpu: 50m
        memory: 100Mi
    sidecars:
      zigbee2mqtt-exporter:
        env:
          ZIGBEE2MQTT_WS: ws://127.0.0.1:8080/api
        image: ghcr.io/tyriis/zigbee2mqtt-exporter:v0.2.7
        ports:
          - containerPort: 3000
            name: http-prom
            protocol: TCP
