---
# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: New Repo Request
description: Request to create a new repository in github
title: "[New Repository] add {{ name }}"
labels:
  - repo-request
assignees: tyriis


body:
  - type: input
    id: name
    attributes:
      label: Name of the repository
      description: Enter the name of the repository
      placeholder: my-new-repo
