# name: Pull Request on Branch Push
# on:
#   push:
#     branches-ignore:
#       - staging
#       - launchpad
#       - production
# jobs:
#   auto-pull-request:
#     name: PullRequestAction
#     runs-on: ubuntu-latest
#     steps:
#       - name: pull-request-action
#         uses: vsoch/pull-request-action@master
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#           BRANCH_PREFIX: "update/"
#           PULL_REQUEST_BRANCH: "master"


name: Pull Request Action
on:
  push:
    branches:
      - '- "[A-Z]+-[0-9]+_(new|bugfix|release|hotfix)_([a-z0-9]+_)+[a-z0-9]+"'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: '[Example] Simple demo',
              owner,
              repo,
              head: '${{ github.ref_name }}',
              base: 'develop',
              body: [
                'This PR is auto-generated by',
                '[actions/github-script](https://github.com/actions/github-script).'
              ].join('\n')
            });
            github.rest.issues.addLabels({
              owner,
              repo,
              issue_number: result.data.number,
              labels: ['feature', 'automated pr']
            });