name: Auto PR
on:
  push:
    branches:
      - release/**

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
        - uses: actions/checkout@v3
      # - name: pull-request-action
      #   uses: vsoch/pull-request-action@1.0.19
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     PULL_REQUEST_BRANCH: "main"
      #     PULL_REQUEST_UPDATE: "false"
        - run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v4
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            base: main
