name: Pull Request Action
on:
  push:
    branches:
      - "[A-Z]+-[0-9]+_(new|bugfix|release|hotfix)*"
      # - ABC-123_new_test_ci3

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_UPDATE: "true"