---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Test Create YAML and PR Workflow

on:
  issues:
    types:
      - opened

jobs:
  test-create-yaml-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test Check for label
        run: |
          if [[ $(jq '.issue.labels[].name' $GITHUB_EVENT_PATH) == *"repo-request"* ]]; then
            echo "Label found"
          else
            echo "Label not found"
            exit 1
          fi

      - name: Test Check for user
        run: |
          USER=$(jq '.issue.user.login' $GITHUB_EVENT_PATH)
          if [[ $USER == '"tyriis"' ]]; then
            echo "$USER is allowed to create YAML"
          else
            echo "$USER is not allowed to create YAML"
            exit 1
          fi

      - name: Close issue on failure
        if: failure()
        run: |
          if [[ $(jq '.issue.labels[].name' $GITHUB_EVENT_PATH) == *"repo-request"* ]]; then
            echo "Closing issue"
            gh issue close ${{ github.event.issue.number }}
            exit 1
          fi
