---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Create YAML and PR

on:
  issues:
    types: [opened]

jobs:
  create-yaml-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
          if [[ $(jq '.issue.labels[].name' $GITHUB_EVENT_PATH) == *"repo-request"* ]]; then
            echo "Label found"
          else
            echo "Label not found"
            exit 1
          fi
      # run only if the issue creator is tyriis or jazzlyn
      # - name: Check for user
      #   run: |
      #     if [[ $(jq '.issue.user.login' $GITHUB_EVENT_PATH) == "tyriis" || $(jq '.issue.user.login' $GITHUB_EVENT_PATH) == "jazzlyn" ]]; then
      #       echo "User found"
      #     else
      #       echo "User not found"
      #       exit 1
      #     fi
      - name: Check for user
        run: |
          if [[ $(jq '.issue.user.login' $GITHUB_EVENT_PATH) == "tyriis" ]]; then
            echo "User found"
          else
            echo "User not found"
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create YAML file
        run: |
          echo "${{ github.event.issue.body }}" | tail -n 1 | xargs echo -n
          echo "data/${{ github.event.issue.number }}.yaml"
