name: PR Labeler
on:
  pull_request:
    types: [opened]
    branches-ignore:
      - main
      - renovate/*

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: TimonVS/pr-labeler-action@v3
        with:
          configuration-path: .github/pr-labeler.yml # optional, .github/pr-labeler.yml is the default value
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}






name: Label Pull Request


on:
  push:
    # regex does not work, unclear why, so we ignore main and renovate/* branches all others will create a pr
    # branches:
    #   - "[A-Z]+-[0-9]+_(new|bugfix|release|hotfix)[a-z0-9_-]+"
    branches-ignore:
      - main
      - renovate/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: auto-pull-request
        uses: vsoch/pull-request-action@1.0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_UPDATE: "true"
