---
name: NPM test

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - run: npm ci
      - run: npm run lint
      - run: npm audit --production
      - run: npm run test
      - run: npm run build
      # - run: npm run start
      # - run: npm run e2e test
