name: Pull Request Action
on:
  push:
    # regex does not work, unclear why, so we ignore main, wip/* and renovate/* branches all others will create a pr
    # branches:
    #   - "[A-Z]+-[0-9]+_(new|bugfix|release|hotfix)[a-z0-9_-]+"
    branches-ignore:
      - main
      - renovate/*
      - wip/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: pull-request-action
        uses: vsoch/pull-request-action@1.0.19
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_BRANCH: "main"
          PULL_REQUEST_UPDATE: "false"
