---
name: Release
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  demo:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF > test.log
      - run: echo "::set-output name=mix-test::$(cat test.log)"
      - run: env