name: Test Action
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  hello_world_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: tyriis/autoversion-release@v1.3
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"