name: Test Action
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  semantic_version_detect:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Semantic Version detection
    steps:
      - name: Detect release type
        id: detect
        uses: tyriis/autoversion-release@v1.15
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `detectRelease` step
      - name: Get the output releaseType
        run: echo "The releaseType was ${{ steps.detect.outputs.releaseType }}"
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        name: Setup Dependency Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        run: npm ci
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        run: npm audit --production
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        run: npm run test
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        run: npm version ${{ steps.detectRelease.outputs.releaseType }}
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Release: ${{ steps.detectRelease.outputs.releaseType }}'
