name: Test Action
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  semantic_version_detect:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Semantic Version detection
    steps:
      - name: Detect release type
        id: detectRelease
        uses: tyriis/autoversion-release@v1.15
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `detectRelease` step
      - name: Get the output releaseType
        run: echo "The releaseType was ${{ steps.detectRelease.outputs.releaseType }}"