name: Test Action
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  semantic_version_detect:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Semantic Version detection
    steps:
      - name: Detect release type
        id: detect
        uses: tyriis/autoversion-release@v1.16
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `detectRelease` step
      - name: Get the output releaseType
        run: echo "The releaseType was ${{ steps.detect.outputs.releaseType }}"
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        uses: actions/checkout@v3
        with:
          ref: main
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - if:  ${{ steps.detect.outputs.releaseType != 'skip' }}
        name: Setup Dependency Cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-
      - if: ${{ steps.detect.outputs.releaseType != 'skip' }}
        run: npm ci
      - if: ${{ steps.detect.outputs.releaseType != 'skip' }}
        run: npm audit --production
      - if: ${{ steps.detect.outputs.releaseType != 'skip' }}
        run: npm run test
      - if: ${{ steps.detect.outputs.releaseType != 'skip' }}
        run: npm version ${{ steps.detect.outputs.releaseType }}
      - if: ${{ steps.detect.outputs.releaseType != 'skip' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Release: ${{ steps.detect.outputs.releaseType }}'
          branch: main
      - if: ${{ steps.detect.outputs.releaseType != 'skip' }}
        name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ steps.detect.outputs.releaseType }}
          git-tag-version: 'true'
        # run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
