name: Test Action
on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  hello_world_job:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: tyriis/autoversion-release@v1.14
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Use the output from the `hello` step
      - name: Get the output releaseType
        run: echo "The releaseType was ${{ steps.hello.outputs.releaseType }}"