---
    name: Version

    on:
      workflow_dispatch:
        inputs:
          message:
            description: Commit message
            required: true
            type: string

    jobs:
      version:
        name: version
        runs-on: ubuntu-latest
        steps:
          # https://github.com/marketplace/actions/github-app-token
        #   - name: Generate Token
        #     uses: tibdex/github-app-token@v1.8.0
        #     id: generate-token
        #     with:
        #       app_id: "${{ secrets.BOT_APP_ID }}"
        #       private_key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

          # https://github.com/marketplace/actions/checkout
          - name: Checkout
            uses: actions/checkout@v3.5.3

          - name: npm version patch
            run: |
              npm --no-git-tag-version version patch

          - name: git add files
            run: |
              git add package.json package-lock.json

          - name: git status
            run: |
              git status --short

          - name: commit
            uses: tyriis/multi-file-commit@v0.1.7
            with:
              # The commit message for the commit.
              message: ${{ inputs.message }}